export const categories = [
  "Business",
  "Finance",
  "CRM",
  "Shopping",
  "Artificial Intelligence",
  "Education",
  "Food & Drink",
  "Health & Fitness",
  "Lifestyle",
  "Entertainment",
  "Travel & Transportation",
  "Communication",
  "Crypto & Web3",
  "Social Networking",
  "Medical",
];
